apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-envars-test
spec: # DeploymentSpec
  selector:
    matchLabels:
      purpose: test-secret-access
  replicas: 2
  template: # PodTemplateSpec
    metadata:
      labels:
        purpose: test-secret-access
    spec: # PodSpec
      containers:
        - name: envars-test-container
          image: nginx
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: password
          volumeMounts:
              # name must match the volume name below
              - name: secret-volume
                mountPath: /etc/secret-volume
      # The secret data is exposed to Containers in the Pod through a Volume.
      volumes:
        - name: secret-volume
          secret:
            secretName: test-secret
