# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kubernetes
url: https://kubernetes.io
host: localhost
port: 7200
description: Production-Grade Container Orchestration
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
incremental: true

safe: false
lsi: false
defaults:
  -
    scope:
      path: ""
    values:
      fullversion: "v1.9.0"
      version: "v1.9"
      githubbranch: "master"
      docsbranch: "master"
      versions:
        - fullversion: "v1.9.0"
          version: "v1.9"
          githubbranch: "v1.9.0"
          docsbranch: "release-1.9"
          url: https://kubernetes.io/_i18n/en/docs/home/
        - fullversion: "v1.8.4"
          version: "v1.8"
          githubbranch: "v1.8.4"
          docsbranch: "release-1.8"
          url: https://v1-8.docs.kubernetes.io/docs/home/
        - fullversion: "v1.7.6"
          version: "v1.7"
          githubbranch: "v1.7.6"
          docsbranch: "release-1.7"
          url: https://v1-7.docs.kubernetes.io/docs/home/
        - fullversion: "v1.6.8"
          version: "v1.6"
          githubbranch: "v1.6.8"
          docsbranch: "release-1.6"
          url: https://v1-6.docs.kubernetes.io/docs/home/
        - fullversion: "v1.5.7"
          version: "v1.5"
          githubbranch: "v1.5.7"
          docsbranch: "release-1.5"
          url: https://v1-5.docs.kubernetes.io/docs/
      deprecated: false
      currentUrl: https://kubernetes.io/docs/home/
      nextUrl: http://kubernetes-io-vnext-staging.netlify.com/
  -
    scope:
      path: "_i18n/en/docs"
    values:
      layout: docwithnav
      showedit: true

permalink: pretty
#description: >- # this means to ignore newlines until "baseurl:"
 # Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-multiple-languages-plugin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# empty array for tabs
emptyArray: []

# Tables of contents, stored in the _data folder, that control the sidebar nav
tocs:
  - docs-home
  - setup
  - tasks
  - tutorials
  - concepts
  - reference
  - samples
  - search

# Jekyll Multilanguage config
languages: ["en", "cn"]
exclude_from_localizations: ["assets", "robots.txt"]
defaultLang: en
languageNames:
  cn: Chinese
  en: English
