apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ssd
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      nodeSelector:
        ssd: "true"
      containers:
        - name: nginx
          image: nginx:latest