apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: config
          mountPath: /etc/a
          subPath: a
        - name: config
          mountPath: /etc/b
          subPath: b
  volumes:
    - name: config
      persistentVolumeClaim:
        claimName: test-nfs-claim
