apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  annotations:
    # docker/default 標識 seccomp 的配置檔案，但它與 Docker 執行時沒有特別關聯
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  # 防止許可權升級到 root
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  # 允許的核心卷型別.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    # 假設叢集管理員設定的臨時 CSI 驅動程式和持久卷可以安全使用
    - 'csi'
    - 'persistentVolumeClaim'
    - 'ephemeral'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # 要求容器在沒有 root 許可權的情況下執行
    rule: 'MustRunAsNonRoot'
  seLinux:
    # 此策略假定節點使用 AppArmor 而不是 SELinux
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # 禁止新增 root 組
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # 禁止新增 root 組
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false

