apiVersion: v1
kind: Pod
metadata:
  name: secret-multiple-envars
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: BACKEND_USERNAME
      valueFrom:
        secretKeyRef:
          name: backend-user
          key: backend_username
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-user
          key: db_username
