apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      # Use an Init Container to clone the git repo to an empty directory
      - name: clone
        image: alpine/git # Any image with git will do
        command:
        - /usr/local/git/git-clone.sh
        args:
        - "https://github.com/my/repo.git"
        - "tags/v1.0.2"
        - "/mypath"
        volumeMounts:
        - name: git-clone
          mountPath: /usr/local/git
        - name: git-volume
          mountPath: /mypath
      containers:
      # Pod's container now has access to the cloned repo
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /mypath
          name: git-volume
      volumes:
      - name: git-volume
        emptyDir: {}
      - name: git-clone
        configMap:
          name: git-clone
          defaultMode: 0755
