apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment

spec:              # DeploymentSpec
  replicas: 2

  template:        # PodTemplateSpec
    metadata:
      labels:
        pod-is-for: kubectl-exec-demo

    spec:          # PodSpec

      volumes:
      - name: redis-persistent-storage
        emptyDir: {}

      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data/redis

        command: ["/bin/sh", "-c", "echo Hello > /data/redis/testfile"]


