apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis

spec:         # DeploymentSec
  replicas: 1

  selector:   # LabelSelector
    matchLabels:
      controller-selector: kubectl-exec-demo
 
  template:   # PodTemplate

    metadata:
      labels:
        controller-selector: kubectl-exec-demo

    spec:     # PodSpec

      volumes:
      - name: redis-persistent-storage
        emptyDir: {}

      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /data/redis


